services:
  - type: worker
    name: discord-music-bot
    env: python
    runtime: python-3.11.9
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python -m bot.main"
    autoDeploy: true
    region: oregon
